# AUTOGENERATED FILE - DO NOT EDIT
# Built by: for_gpt_builder.py
# Built at (UTC): 2026-04-30T12:11:20+00:00
#
# Contents: project files inlined with separators.

FILES = [
    'db/database.py',
    'main.py',
    'models/appointments.py',
    'models/base.py',
    'models/business.py',
    'models/clients.py',
    'models/service.py',
    'models/staffs.py',
    'repository/repository.py',
    'routers/route.py',
    'schemas/appointment.py',
    'services/service.py',
    'utils/free_slots.py',
    'utils/logger.py',
]

========================================================================================
# FILE: db/database.py (594 bytes)
========================================================================================
from typing import Annotated
import os
from dotenv import load_dotenv

load_dotenv()

from fastapi import Depends
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker, create_async_engine


DATABASE_URL = os.getenv("DATABASE_URL")
if not DATABASE_URL:
    DATABASE_URL = "sqlite+aiosqlite:///./test.db"

engine = create_async_engine(DATABASE_URL)
new_session = async_sessionmaker(engine, expire_on_commit=False)


async def get_session():
  async with new_session() as session:
    yield session


SessionDep = Annotated[AsyncSession, Depends(get_session)]

========================================================================================
# FILE: main.py (5891 bytes)
========================================================================================
# main.py - точка входа в приложение, где создается экземпляр FastAPI и подключаются роуты

from contextlib import asynccontextmanager
from fastapi import FastAPI, HTTPException
from fastapi.responses import JSONResponse
import uvicorn
from fastapi.middleware import Middleware
from fastapi.middleware.cors import CORSMiddleware
from starlette.middleware.base import BaseHTTPMiddleware

from app.routers.route import main_router
from app.utils.logger import logger
from app.db.database import engine
from app.models.base import Base
from app.models.business import BusinessModel
from app.db.database import new_session


@asynccontextmanager
async def lifespan(app: FastAPI):
    # Startup
    # Создаем все таблицы в БД
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)
    
    # Создаем тестовый бизнес, если его нет
    async with new_session() as session:
        from sqlalchemy import select
        from app.models.staffs import StaffModel
        from app.models.service import ServiceModel
        
        result = await session.execute(
            select(BusinessModel).where(BusinessModel.name == "Test Business")
        )
        test_business = result.scalars().first()
        
        if not test_business:
            test_business = BusinessModel(
                name="Test Business",
                owner_tg_id=123456789,
                api_key="test-api-key-12345"
            )
            session.add(test_business)
            await session.commit()
            await session.refresh(test_business)
            logger.info("Created test business with API key: test-api-key-12345")
        else:
            logger.info(f"Test business already exists, API key: {test_business.api_key}")
        
        # Создаем тестовых сотрудников, если их нет
        staff_result = await session.execute(
            select(StaffModel).where(StaffModel.business_id == test_business.id)
        )
        existing_staffs = staff_result.scalars().all()
        
        if not existing_staffs:
            staff1 = StaffModel(
                name="Иван Иванов",
                business_id=test_business.id,
                role="Мастер маникюра"
            )
            staff2 = StaffModel(
                name="Мария Петрова",
                business_id=test_business.id,
                role="Парикмахер"
            )
            session.add(staff1)
            session.add(staff2)
            await session.commit()
            logger.info("Created test staffs")
        else:
            logger.info(f"Test staffs already exist: {len(existing_staffs)} staffs")
        
        # Создаем тестовые услуги, если их нет
        service_result = await session.execute(
            select(ServiceModel).where(ServiceModel.business_id == test_business.id)
        )
        existing_services = service_result.scalars().all()
        
        if not existing_services:
            service1 = ServiceModel(
                name="Маникюр",
                business_id=test_business.id,
                price=1500,
                description="Классический маникюр",
                duration_minutes=60
            )
            service2 = ServiceModel(
                name="Стрижка",
                business_id=test_business.id,
                price=2000,
                description="Мужская/женская стрижка",
                duration_minutes=45
            )
            service3 = ServiceModel(
                name="Окрашивание",
                business_id=test_business.id,
                price=3500,
                description="Окрашивание волос",
                duration_minutes=120
            )
            session.add(service1)
            session.add(service2)
            session.add(service3)
            await session.commit()
            logger.info("Created test services")
        else:
            logger.info(f"Test services already exist: {len(existing_services)} services")
    
    yield
    
    # Shutdown (если нужно что-то делать при остановке)


app = FastAPI(title="SaaS Appointment Booking API", version="1.0.0", lifespan=lifespan)
app.include_router(main_router, prefix="/api/v1")


class LoggingMiddleware(BaseHTTPMiddleware):
    async def dispatch(self, request, call_next):
        logger.info(f"{request.method} {request.url.path}")
        try:
            response = await call_next(request)
            logger.info(f"Response: {response.status_code}")
            return response
        except Exception as e:
            logger.error(f"Middleware error: {str(e)}")
            raise

app.add_middleware(LoggingMiddleware)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
    allow_credentials=True,
)


@app.exception_handler(Exception)
async def general_exception_handler(request, exc):
    logger.error(f"Unhandled exception: {type(exc).__name__} - {str(exc)}", exc_info=True)
    return JSONResponse(
        status_code=500,
        content={"detail": "Internal server error"}
    )


@app.exception_handler(HTTPException)
async def http_exception_handler(request, exc):
    logger.warning(f"HTTP exception: {exc.status_code} - {exc.detail}")
    return JSONResponse(
        status_code=exc.status_code,
        content={"detail": exc.detail}
    )


if __name__ == "__main__":
  uvicorn.run("app.main:app", reload=True)

========================================================================================
# FILE: models/appointments.py (1056 bytes)
========================================================================================
# Модель данных для записей

from sqlalchemy import Column, DateTime, ForeignKey, Integer, String
from sqlalchemy.orm import relationship

from app.models.base import Base

class AppointmentModel(Base):
  __tablename__ = 'appointments'

  id = Column(Integer, primary_key=True)
  business_id = Column(Integer, ForeignKey('businesses.id'), nullable=False)
  client_id = Column(Integer, ForeignKey('clients.id'), nullable=False)
  staff_id = Column(Integer, ForeignKey('staffs.id'), nullable=False)
  service_id = Column(Integer, ForeignKey('services.id'), nullable=False)
  start_time = Column(DateTime, nullable=False)
  end_time = Column(DateTime, nullable=False)
  status = Column(String, nullable=False, default='scheduled')

  client = relationship('ClientModel', back_populates='appointments')
  staff = relationship('StaffModel', back_populates='appointments')
  business = relationship('BusinessModel', back_populates='appointments')
  service = relationship('ServiceModel', back_populates='appointments')

========================================================================================
# FILE: models/base.py (84 bytes)
========================================================================================
from sqlalchemy.orm import DeclarativeBase

class Base(DeclarativeBase):
    pass

========================================================================================
# FILE: models/business.py (989 bytes)
========================================================================================
# Модель данных для бизнесов

from sqlalchemy import Boolean, Column, DateTime, Integer, String
from sqlalchemy.orm import relationship
from datetime import datetime
import uuid

from app.models.base import Base

class BusinessModel(Base):
  __tablename__ = 'businesses'

  id = Column(Integer, primary_key=True)
  name = Column(String, nullable=False)
  created_at = Column(DateTime, default=datetime.now)
  is_active = Column(Boolean, default=True)
  owner_tg_id = Column(Integer, nullable=False)
  api_key = Column(String, default=lambda: str(uuid.uuid4()), unique=True)

  staffs = relationship('StaffModel', back_populates='business', cascade='all, delete')
  services = relationship('ServiceModel', back_populates='business', cascade='all, delete')
  clients = relationship('ClientModel', back_populates='business', cascade='all, delete')
  appointments = relationship('AppointmentModel', back_populates='business', cascade='all, delete')

========================================================================================
# FILE: models/clients.py (837 bytes)
========================================================================================
# Модель данных для клиентов

from datetime import datetime
from pydantic import EmailStr, Field
from app.models.base import Base
from sqlalchemy import Column, DateTime, Integer, String, ForeignKey, UniqueConstraint
from sqlalchemy.orm import relationship


class ClientModel(Base):
    __tablename__ = 'clients'

    id = Column(Integer, primary_key=True)
    name = Column(String, nullable=False)
    phone = Column(String, nullable=True)
    tg_id = Column(Integer, nullable=False)
    business_id = Column(Integer, ForeignKey('businesses.id'), nullable=False)
    created_at = Column(DateTime, default=datetime.now)

    appointments = relationship('AppointmentModel', back_populates='client', cascade='all, delete')
    business = relationship('BusinessModel', back_populates='clients')

========================================================================================
# FILE: models/service.py (699 bytes)
========================================================================================
# Модель данных для услуг

from sqlalchemy import Column, Integer, ForeignKey, String
from sqlalchemy.orm import relationship

from app.models.base import Base

class ServiceModel(Base):
  __tablename__ = 'services'

  id = Column(Integer, primary_key=True)
  business_id = Column(Integer, ForeignKey('businesses.id'), nullable=False)
  name = Column(String, nullable=False)
  price = Column(Integer, nullable=False)
  description = Column(String, nullable=True)
  duration_minutes = Column(Integer, nullable=True)

  business = relationship('BusinessModel', back_populates='services')
  appointments = relationship('AppointmentModel', back_populates='service')

========================================================================================
# FILE: models/staffs.py (624 bytes)
========================================================================================
# Модель данных для сотрудников

from sqlalchemy import Column, Integer, String, ForeignKey
from sqlalchemy.orm import relationship

from app.models.base import Base

class StaffModel(Base):
  __tablename__ = 'staffs'

  id = Column(Integer, primary_key=True)
  name = Column(String, nullable=False)
  business_id = Column(Integer, ForeignKey('businesses.id'), nullable=False)
  role = Column(String, nullable=False)

  business = relationship('BusinessModel', back_populates='staffs')
  appointments = relationship('AppointmentModel', back_populates='staff', cascade='all, delete')

========================================================================================
# FILE: repository/repository.py (8535 bytes)
========================================================================================
# Repository для работы с базой данных, инкапсулирующий логику доступа к данным и проверки бизнес-правил

from datetime import datetime, timedelta, timezone
from sqlalchemy import select
from sqlalchemy.orm import selectinload
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.appointments import AppointmentModel
from app.models.service import ServiceModel
from app.models.staffs import StaffModel
from app.models.clients import ClientModel
from app.models.business import BusinessModel
from app.schemas.appointment import AppointmentCreateSchema


class Repository:
    def __init__(self, session: AsyncSession):
        self.session = session

    # Получаем список сотрудников для бизнеса
    async def get_business_staffs(self, business_id: int) -> list[StaffModel]:
        try:
            staffs = await self.session.execute(
              select(StaffModel)
              .where(StaffModel.business_id == business_id)
            )
            return staffs.scalars().all()
        except Exception as e:
            raise Exception("Internal Server Error")
        

    # Проверяем принадлежность клиента и сотрудника к бизнесу
    async def client_and_staff_exists(self, business_id: int, client_id: int, staff_id: int) -> bool:
        try:
            client_result = await self.session.execute(
                select(ClientModel)
                .where(ClientModel.business_id == business_id)
                .where(ClientModel.id == client_id)
            )
            staff_result = await self.session.execute(
                select(StaffModel)
                .where(StaffModel.business_id == business_id)
                .where(StaffModel.id == staff_id)
            )

            if not client_result.scalars().first():
                return False
                
            if not staff_result.scalars().first():
                return False

            return True
        
        except Exception as e:
            raise Exception("Internal Server Error")


    # Проверяем нет ли пересечений с существующими записями для этого сотрудника
    async def has_overlapping_appointments(self, business_id: int, appointment_data: AppointmentCreateSchema) -> bool:
        try: 
            result = await self.session.execute(
            select(AppointmentModel).limit(1)
            .where(AppointmentModel.business_id == business_id)
            .where(AppointmentModel.staff_id == appointment_data.staff_id)
            .where(
                (AppointmentModel.start_time < appointment_data.end_time) &
                (AppointmentModel.end_time > appointment_data.start_time)
            )
            )

            if result.scalars().first() is not None:
                return True
        
        except Exception as e:
            raise Exception("Internal Server Error")
        
        return False
    

    # Получаем занятые слоты для сотрудника в заданный день
    async def get_busy_slots(self, business_id: int, staff_id: int, date: datetime) -> list[AppointmentModel]:
        start_of_day = datetime(date.year, date.month, date.day, tzinfo=timezone.utc)
        next_day = start_of_day + timedelta(days=1)

        try:
            result = await self.session.execute(
                select(AppointmentModel)
                .where(AppointmentModel.business_id == business_id)
                .where(AppointmentModel.staff_id == staff_id)
                .where(AppointmentModel.status == "scheduled")
                .where(AppointmentModel.start_time > datetime.now(timezone.utc))
                .where(
                (AppointmentModel.start_time < next_day) &
                (AppointmentModel.end_time > start_of_day)
                )
            )

            return result.scalars().all()
        except Exception as e:
            raise Exception("Internal Server Error")
    

    # Получаем все записи клиента
    async def get_client_appointments(self, business_id: int, client_id: int) -> list[AppointmentModel]:
      try:
        # Очищаем кэш сессии перед запросом
        self.session.expire_all()
        
        result = await self.session.execute(
            select(AppointmentModel).order_by(AppointmentModel.start_time.desc()).options(
                selectinload(AppointmentModel.client),
                selectinload(AppointmentModel.staff),
                selectinload(AppointmentModel.service)
            )
            .where(AppointmentModel.business_id == business_id)
            .where(AppointmentModel.client_id == client_id)
            .where(AppointmentModel.status == 'scheduled')
            .where(AppointmentModel.start_time > datetime.now(timezone.utc))
        )

        return result.scalars().all()
      
      except Exception as e:
        raise Exception("Internal Server Error")

    
    # Получаем все услуги бизнеса
    async def get_business_services(self, business_id: int) -> list[ServiceModel]:
        try:
            result = await self.session.execute(
                select(ServiceModel)
                .where(ServiceModel.business_id == business_id)
            )

            return result.scalars().all()
        except Exception as e:
            raise Exception("Internal Server Error")


    # Добавляем новую запись в базу данных
    async def add_appointment(self, appointment: AppointmentModel) -> AppointmentModel:
      try: 
        self.session.add(appointment)
        return appointment
      except Exception as e:
        await self.session.rollback()
        raise Exception("Internal Server Error")
      

    # Отмена записи клиента
    async def cancelled_appointment(self, appointment: AppointmentModel) -> dict:
        try:
            appointment.status = "cancelled"
            return {"success": "OK"}
        except Exception as e:
            await self.session.rollback()
            raise Exception("Internal Server Error")


    # Ищем запись по id
    async def get_appointment_by_id(self, business_id: int, client_id: int, appointment_id: int) -> AppointmentModel:
      try:
        result = await self.session.execute(
            select(AppointmentModel)
            .where(AppointmentModel.business_id == business_id)
            .where(AppointmentModel.client_id == client_id)
            .where(AppointmentModel.id == appointment_id)
            .where(AppointmentModel.status == "scheduled")
            .where(AppointmentModel.start_time > datetime.now(timezone.utc))
        )

        return result.scalars().first()
      
      except Exception as e:
        raise Exception("Internal Server Error")
      
      
    # Получение или создание клиента
    async def get_or_create_client(self, business_id: int, tg_id: int, client_name: str) -> ClientModel:
      try:
        result = await self.session.execute(
            select(ClientModel)
            .where(ClientModel.business_id == business_id)
            .where(ClientModel.tg_id == tg_id)
        )

        client = result.scalars().first()

        if client:
            return client
        
        new_client = ClientModel(
            name=client_name,
            tg_id=tg_id,
            business_id=business_id
        )

        self.session.add(new_client)
        await self.session.commit()
        await self.session.refresh(new_client)

        return new_client
      
      except Exception as e:
        await self.session.rollback()
        raise Exception("Internal Server Error")


    # Получаем бизнес по API Key
    async def get_business_by_api_key(self, api_key: str) -> BusinessModel | None:
        try:
            result = await self.session.execute(
                select(BusinessModel)
                .where(BusinessModel.api_key == api_key)
            )
            return result.scalars().first()
        except Exception as e:
            raise Exception("Internal Server Error")

========================================================================================
# FILE: routers/route.py (7382 bytes)
========================================================================================
# Endpoint'ы для работы с бизнесом, сотрудниками, клиентами и записями

from datetime import datetime, timedelta, timezone
from fastapi import APIRouter, Depends, HTTPException, Header

from app.db.database import SessionDep
from app.models.appointments import AppointmentModel
from app.models.clients import ClientModel
from app.models.service import ServiceModel
from app.models.staffs import StaffModel
from app.models.business import BusinessModel
from app.schemas.appointment import AppointmentCreateSchema
from app.services.service import Service
from app.repository.repository import Repository
from app.utils.free_slots import get_free_slots

main_router = APIRouter()


"""----- Проверка API Key -----"""
async def get_current_business(session: SessionDep, x_api_key: str = Header(...)) -> BusinessModel:
    repository = Repository(session)
    service = Service(session, repository)
    business = await service.get_business_by_api_key(x_api_key)
    if not business:
        raise HTTPException(status_code=401, detail="Invalid API Key")
    return business


"""----- Получение сотрудников бизнеса -----"""
@main_router.get("/staffs/")
async def get_staffs(session: SessionDep, business: BusinessModel = Depends(get_current_business)):
    try:
        repository = Repository(session)
        service = Service(session, repository)
        staffs = await service.get_business_staffs(business.id)
        return staffs
    except Exception as e:
        raise HTTPException(status_code=500, detail="Internal Server Error")
    

"""----- Получение услуг для бизнеса -----"""
@main_router.get("/services/")
async def get_services(session: SessionDep, business: BusinessModel = Depends(get_current_business)):
    try:
        repository = Repository(session)
        service = Service(session, repository)
        services = await service.get_business_services(business.id)
        return services
    except Exception as e:
        raise HTTPException(status_code=500, detail="Internal Server Error")
    

"""----- Получение свободных дней для сотрудника на месяц -----"""
@main_router.get("/staffs/{staff_id}/free-days/")
async def get_free_days(session: SessionDep, staff_id: int, business: BusinessModel = Depends(get_current_business)):
    try:
        repository = Repository(session)
        service = Service(session, repository)
        
        # Начинаем с сегодняшнего дня
        now = datetime.now(timezone.utc)
        today = now.replace(hour=0, minute=0, second=0, microsecond=0)
        free_days = []

        # Проверяем 30 дней вперед
        for i in range(30):
            check_date = today + timedelta(days=i)
            
            # Если это сегодня, проверяем не закончился ли рабочий день
            if i == 0:
                work_end = check_date.replace(hour=18, minute=0, second=0, microsecond=0)
                if now >= work_end:
                    # Рабочий день закончился, пропускаем сегодня
                    continue
            
            busy_slots = await service.get_busy_slots(business.id, staff_id, check_date)
            free_slots = await get_free_slots(busy_slots, check_date)
            
            # Если есть хотя бы один свободный слот, добавляем день
            if free_slots:
                free_days.append({
                    "date": check_date.strftime("%Y-%m-%d"),
                    "slots_count": len(free_slots)
                })
        
        return free_days
    except Exception as e:
        raise HTTPException(status_code=500, detail="Internal Server Error")
    

"""----- Получение свободных слотов для сотрудника в заданный день -----"""
@main_router.get("/staffs/{staff_id}/free-slots/")
async def get_available_slots(session: SessionDep, staff_id: int, date: str, business: BusinessModel = Depends(get_current_business)):
    try:
        from datetime import datetime
        # Парсим строку даты в datetime объект (формат YYYY-MM-DD)
        date_obj = datetime.strptime(date, "%Y-%m-%d")
        
        repository = Repository(session)
        service = Service(session, repository)
        busy_slots = await service.get_busy_slots(business.id, staff_id, date_obj)
        free_slots = await get_free_slots(busy_slots, date_obj)
        
        return free_slots
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail="Internal Server Error")
    

"""----- Получение всех записей клиента -----"""
@main_router.get("/clients/{client_id}/appointments/")
async def get_client_appointments(session: SessionDep, client_id: int, business: BusinessModel = Depends(get_current_business)):
    try:
        repository = Repository(session)
        service = Service(session, repository)
        appointments = await service.get_client_appointments(business.id, client_id)
        return appointments
    except Exception as e:
        raise HTTPException(status_code=500, detail="Internal Server Error")


"""----- Создание новой записи -----"""
@main_router.post("/appointments/")
async def create_appointment(session: SessionDep, appointment_data: AppointmentCreateSchema, business: BusinessModel = Depends(get_current_business)):
    try:
        repository = Repository(session)
        service = Service(session, repository)
        new_appointment = await service.create_appointment(business.id, appointment_data)
        return new_appointment
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail="Internal Server Error")


"""----- Получение или создание клиента -----"""
@main_router.post("/clients/get-or-create/")
async def get_or_create_client(session: SessionDep, tg_id: int, client_name: str, business: BusinessModel = Depends(get_current_business)):
    try:
        repository = Repository(session)
        service = Service(session, repository)
        client = await service.get_or_create_client(business.id, tg_id, client_name)
        return client
    except Exception as e:
        raise HTTPException(status_code=500, detail="Internal Server Error")


"""----- Отмена записи клиента -----"""
@main_router.post("/clients/{client_id}/appointments/{appointment_id}/")
async def cancelled_appointment(session: SessionDep, client_id: int, appointment_id: int, business: BusinessModel = Depends(get_current_business)):
    try:
        repository = Repository(session)
        service = Service(session, repository)
        await service.cancelled_appointment(business.id, client_id, appointment_id)
        return {"message": "Запись успешно удалена"}
    except Exception as e:
        raise HTTPException(status_code=500, detail="Internal Server Error")

========================================================================================
# FILE: schemas/appointment.py (863 bytes)
========================================================================================
from pydantic import BaseModel, Field, field_validator
from datetime import datetime

class AppointmentCreateSchema(BaseModel):
    client_id: int = Field(..., description="ID клиента")
    staff_id: int = Field(..., description="ID сотрудника")
    service_id: int = Field(..., description="ID услуги")
    start_time: datetime = Field(..., description="Время начала записи")
    end_time: datetime = Field(..., description="Время окончания записи")
    
    @field_validator('end_time')
    @classmethod
    def validate_time_range(cls, end_time: datetime, info) -> datetime:
        start_time = info.data.get('start_time')
        if start_time and end_time <= start_time:
            raise ValueError('end_time должно быть больше start_time')
        return end_time

========================================================================================
# FILE: services/service.py (7617 bytes)
========================================================================================
from datetime import datetime, timezone
from uuid import uuid4
from fastapi import HTTPException
from sqlalchemy import delete, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.appointments import AppointmentModel
from app.models.clients import ClientModel
from app.models.service import ServiceModel
from app.models.staffs import StaffModel
from app.models.business import BusinessModel
from app.schemas.appointment import AppointmentCreateSchema
from app.repository.repository import Repository
from app.utils.logger import logger


class Service:
  def __init__(self, session: AsyncSession, repository: Repository):
      self.session = session
      self.repository = repository


  # Получаем список сотрудников для бизнеса
  async def get_business_staffs(self, business_id: int) -> list[StaffModel]:
    try: 
      staffs = await self.repository.get_business_staffs(business_id)
      if not staffs:
        logger.info(f"No staffs found for business_id={business_id}")
      return staffs
    except Exception as e:
      logger.error(f"Error fetching business staffs: {e}")
      raise HTTPException(status_code=500, detail="Internal Server Error")


  # Получаем занятые слоты для сотрудника в заданный день
  async def get_busy_slots(self, business_id: int, staff_id: int, date: datetime) -> list[AppointmentModel]:
    try:
      appointments = await self.repository.get_busy_slots(business_id, staff_id, date)

      if not appointments:
        logger.info(f"No appointments found for staff_id={staff_id} on {date.date()}")

      return appointments
    
    except Exception as e:
      logger.error(f"Error fetching busy slots: {e}")
      raise HTTPException(status_code=500, detail="Internal Server Error")


  # Получаем все записи клиента
  async def get_client_appointments(self, business_id: int, client_id: int) -> list[AppointmentModel]:
    try: 
      appointments = await self.repository.get_client_appointments(business_id, client_id)

      if not appointments:
        logger.info(f"No appointments found for client_id={client_id} in business_id={business_id}")

      return appointments
    
    except Exception as e:
      logger.error(f"Error fetching client appointments: {e}")
      raise HTTPException(status_code=500, detail="Internal Server Error")
    

    # Получаем все услуги бизнеса
  async def get_business_services(self, business_id: int) -> list[ServiceModel]:
    try:
      services = await self.repository.get_business_services(business_id)

      if not services:
        logger.info(f"No services found for business_id={business_id}")

      return services
      
    except Exception as e:
      logger.error(f"Error fetching business services: {e}")
      raise HTTPException(status_code=500, detail="Internal Server Error")
    

  # Создаем новую запись
  async def create_appointment(self, business_id: int, appointment_data: AppointmentCreateSchema) -> AppointmentModel:
    try:
      # Проверка принадлежности клиента и сотрудника к бизнесу
      client_and_staff_exists = await self.repository.client_and_staff_exists(business_id, appointment_data.client_id, appointment_data.staff_id)

      if not client_and_staff_exists:
        logger.warning(f"Client with id={appointment_data.client_id} or staff with id={appointment_data.staff_id} does not belong to business_id={business_id}")
        raise HTTPException(status_code=400, detail="Client or staff does not belong to this business")

      # Проверяем, нет ли пересечений с существующими записями для этого сотрудника
      has_overlap = await self.repository.has_overlapping_appointments(business_id, appointment_data)
      if has_overlap:
        logger.warning(f"Attempt to create overlapping appointment for staff_id={appointment_data.staff_id} in business_id={business_id}")
        raise HTTPException(status_code=400, detail="Appointment overlaps with existing booking")
          
      # Если все проверки пройдены, создаем запись
      new_appointment = AppointmentModel(
        business_id=business_id,
        client_id=appointment_data.client_id,
        staff_id=appointment_data.staff_id,
        service_id=appointment_data.service_id,
        start_time=appointment_data.start_time,
        end_time=appointment_data.end_time
      )

      await self.repository.add_appointment(new_appointment)
      await self.session.commit()
      await self.session.refresh(new_appointment)
          
      logger.info(f"Created new appointment with id={new_appointment.id} for staff_id={appointment_data.staff_id} in business_id={business_id}")

      return new_appointment
    except HTTPException as http_exc:
      raise http_exc
    
    except Exception as e:
      logger.error(f"Error creating appointment: {e}")
      await self.session.rollback()
      raise HTTPException(status_code=500, detail="Internal Server Error")
    

  # Отмена запись
  async def cancelled_appointment(self, business_id: int, client_id: int, appointment_id: int) -> dict:
    try:
      logger.info(f"Attempting to delete appointment_id={appointment_id} for client_id={client_id} in business_id={business_id}")
      
      # Проверяем, что запись принадлежит этому бизнесу и клиенту
      appointment = await self.repository.get_appointment_by_id(business_id, client_id, appointment_id)

      if not appointment:
        logger.warning(f"Attempt to delete non-existent or unauthorized appointment with id={appointment_id} for client_id={client_id} in business_id={business_id}")
        raise HTTPException(status_code=404, detail="Appointment not found")

      logger.info(f"Found appointment: {appointment.id}, deleting...")
      response = await self.repository.cancelled_appointment(appointment)
      
      logger.info(f"Committing cancelled...")
      await self.session.commit()
      
      logger.info(f"Successfully deleted appointment with id={appointment_id} for client_id={client_id} in business_id={business_id}")

      return response

    except HTTPException as http_exc:
      raise http_exc
    
    except Exception as e:
      logger.error(f"Error deleting appointment: {e}", exc_info=True)
      await self.session.rollback()
      raise HTTPException(status_code=500, detail="Internal Server Error")


  # Получение или создание клиента
  async def get_or_create_client(self, business_id: int, tg_id: int, client_name: str) -> ClientModel:
    try:
      client = await self.repository.get_or_create_client(business_id, tg_id, client_name)
      return client
    except Exception as e:
      logger.error(f"Error getting or creating client: {e}")
      raise HTTPException(status_code=500, detail="Internal Server Error")


  # Получаем бизнес по API Key
  async def get_business_by_api_key(self, api_key: str) -> BusinessModel | None:
    try:
      return await self.repository.get_business_by_api_key(api_key)
    except Exception as e:
      logger.error(f"Error getting business by API key: {e}")
      raise HTTPException(status_code=500, detail="Internal Server Error")

========================================================================================
# FILE: utils/free_slots.py (3164 bytes)
========================================================================================
# Получение свободных слотов для записи

from datetime import datetime, timedelta, timezone
from fastapi import HTTPException

from app.models.appointments import AppointmentModel
from app.utils.logger import logger


async def get_free_slots(
    busy_slots: list[AppointmentModel], 
    date: datetime,
    work_start_hour: int = 9,
    work_end_hour: int = 18,
    step_minutes: int = 30,
    duration_minutes: int = 60
) -> list[str]:
    """
    Генерирует список свободных временных слотов для записи.
    
    """
    try:
        # Убеждаемся, что date имеет timezone
        if date.tzinfo is None:
            date = date.replace(tzinfo=timezone.utc)
        
        # Определяем границы рабочего дня
        work_start = date.replace(hour=work_start_hour, minute=0, second=0, microsecond=0)
        work_end = date.replace(hour=work_end_hour, minute=0, second=0, microsecond=0)
        
        # Получаем текущее время
        now = datetime.now(timezone.utc)
        
        # Генерируем список возможных стартовых точек
        candidate_slots = []
        current_time = work_start
        
        while current_time < work_end:
            slot_end = current_time + timedelta(minutes=duration_minutes)
            
            # Проверяем что слот не выходит за рабочее время И что слот в будущем
            if slot_end <= work_end and current_time > now:
                candidate_slots.append(current_time)
            
            current_time += timedelta(minutes=step_minutes)
        
        # Фильтруем кандидатов: проверяем пересечения с занятыми слотами
        free_slots = []
        
        for slot_start in candidate_slots:
            slot_end = slot_start + timedelta(minutes=duration_minutes)
            is_free = True
            
            # Проверяем пересечение с каждым занятым интервалом
            for busy in busy_slots:
                # Убеждаемся, что времена слотов имеют timezone
                busy_start = busy.start_time if busy.start_time.tzinfo else busy.start_time.replace(tzinfo=timezone.utc)
                busy_end = busy.end_time if busy.end_time.tzinfo else busy.end_time.replace(tzinfo=timezone.utc)
                
                # Проверка пересечения: slot_start < busy_end AND slot_end > busy_start
                if slot_start < busy_end and slot_end > busy_start:
                    is_free = False
                    break
            
            if is_free:
                free_slots.append(slot_start.isoformat())
        
        return free_slots
    
    except Exception as e:
        logger.error(f"Error calculating free slots: {e}")
        raise HTTPException(status_code=500, detail="Internal Server Error")

========================================================================================
# FILE: utils/logger.py (194 bytes)
========================================================================================
import logging

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)

logger = logging.getLogger(__name__)

